/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Model = {
  _id: string;
  _type: "model";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  headshot?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gender?: "female" | "male";
  skin_tone?: string;
  skin_type?: string;
  face_shape?: string;
  hair?: string;
  eye_color?: string;
  lip_size?: "full" | "medium" | "thin";
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  tag?: "top" | "normal";
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  category?: string;
  introduction?: string;
  body?: string;
  conclusion?: string;
  date?: string;
};

export type Markdown = string;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Model | Blog | Markdown | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries.ts
// Variable: BLOGS_QUERY
// Query: *[_type =='blog' && defined(slug.current)] | order(_createdAt desc){        _id,        _type,        _createdAt,        _updatedAt,        _rev,        "slug": slug.current,        date,        image,        title,        introduction    }
export type BLOGS_QUERYResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug: string | null;
  date: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  title: string | null;
  introduction: string | null;
}>;
// Variable: BLOG_DETAILS_QUERY
// Query: *[_type =='blog' && slug.current == $slug][0] {        _id,        _type,        _createdAt,        _updatedAt,        _rev,        title,        "slug": slug.current,        author,        image,        category,        introduction,        body,        conclusion,        date    }
export type BLOG_DETAILS_QUERYResult = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  slug: string | null;
  author: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  category: string | null;
  introduction: string | null;
  body: string | null;
  conclusion: string | null;
  date: string | null;
} | null;
// Variable: HOME_MODELS_QUERY
// Query: *[_type =='model' && defined(slug.current) && tag == 'top'] | order(_createdAt desc) {        _id,        _type,        _createdAt,        _updatedAt,        _rev,        name,        "slug": slug.current,        headshot,        eye_color,        skin_tone,    }
export type HOME_MODELS_QUERYResult = Array<{
  _id: string;
  _type: "model";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: string | null;
  headshot: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  eye_color: string | null;
  skin_tone: string | null;
}>;
// Variable: MODELS_QUERY
// Query: *[_type =='model' && defined(slug.current)] | order(_createdAt) {        _id,        _type,        _createdAt,        _updatedAt,        _rev,        name,        "slug": slug.current,        headshot,        gender,    }
export type MODELS_QUERYResult = Array<{
  _id: string;
  _type: "model";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: string | null;
  headshot: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  gender: "female" | "male" | null;
}>;
// Variable: MODEL_DETAILS_QUERY
// Query: *[_type =='model' && slug.current == $slug][0] {        _id,        _type,        _createdAt,        _updatedAt,        _rev,        name,        "slug": slug.current,        headshot,        gender,        eye_color,        hair,        skin_tone,        skin_type,        face_shape,        lip_size,        "gallery": gallery[].asset->url,    }
export type MODEL_DETAILS_QUERYResult = {
  _id: string;
  _type: "model";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: string | null;
  headshot: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  gender: "female" | "male" | null;
  eye_color: string | null;
  hair: string | null;
  skin_tone: string | null;
  skin_type: string | null;
  face_shape: string | null;
  lip_size: "full" | "medium" | "thin" | null;
  gallery: Array<string | null> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type =='blog' && defined(slug.current)] | order(_createdAt desc){\n        _id,\n        _type,\n        _createdAt,\n        _updatedAt,\n        _rev,\n        \"slug\": slug.current,\n        date,\n        image,\n        title,\n        introduction\n    }": BLOGS_QUERYResult;
    "*[_type =='blog' && slug.current == $slug][0] {\n        _id,\n        _type,\n        _createdAt,\n        _updatedAt,\n        _rev,\n        title,\n        \"slug\": slug.current,\n        author,\n        image,\n        category,\n        introduction,\n        body,\n        conclusion,\n        date\n    }": BLOG_DETAILS_QUERYResult;
    "*[_type =='model' && defined(slug.current) && tag == 'top'] | order(_createdAt desc) {\n        _id,\n        _type,\n        _createdAt,\n        _updatedAt,\n        _rev,\n        name,\n        \"slug\": slug.current,\n        headshot,\n        eye_color,\n        skin_tone,\n    }": HOME_MODELS_QUERYResult;
    "*[_type =='model' && defined(slug.current)] | order(_createdAt) {\n        _id,\n        _type,\n        _createdAt,\n        _updatedAt,\n        _rev,\n        name,\n        \"slug\": slug.current,\n        headshot,\n        gender,\n    }": MODELS_QUERYResult;
    "*[_type =='model' && slug.current == $slug][0] {\n        _id,\n        _type,\n        _createdAt,\n        _updatedAt,\n        _rev,\n        name,\n        \"slug\": slug.current,\n        headshot,\n        gender,\n        eye_color,\n        hair,\n        skin_tone,\n        skin_type,\n        face_shape,\n        lip_size,\n        \"gallery\": gallery[].asset->url,\n    }": MODEL_DETAILS_QUERYResult;
  }
}
